import { Activity, ArrowLeft, Building2, CalendarDays, Plus, UserRound, Users, Stethoscope, Clock3 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { EmptyState } from '../components/EmptyState'
import { PageHeader } from '../components/PageHeader'
import { Breadcrumbs } from '../components/Breadcrumbs'
import { StatusBadge } from '../components/StatusBadge'

export function DashboardPage() {
  return <><Breadcrumbs current="نظرة عامة" /><PageHeader eyebrow="الأحد، 20 سبتمبر 2026" title="مرحبًا بك، أحمد" description="إليك نظرة سريعة على مساحة إدارة Medicare." action={<Link to="/organizations" className="primary-button"><Plus size={18} /> إضافة مؤسسة</Link>} /><div className="stat-grid"><div className="stat-card"><span className="stat-icon blue"><Building2 size={20} /></span><span className="stat-label">المؤسسات</span><strong>—</strong><small>بانتظار الربط</small></div><div className="stat-card"><span className="stat-icon teal"><Stethoscope size={20} /></span><span className="stat-label">العيادات</span><strong>—</strong><small>بانتظار الربط</small></div><div className="stat-card"><span className="stat-icon amber"><UserRound size={20} /></span><span className="stat-label">الأطباء</span><strong>—</strong><small>بانتظار الربط</small></div><div className="stat-card"><span className="stat-icon rose"><CalendarDays size={20} /></span><span className="stat-label">المواعيد</span><strong>—</strong><small>بانتظار الربط</small></div></div><div className="dashboard-grid"><section className="dashboard-panel"><div className="panel-heading"><div><p className="eyebrow">النشاط</p><h2>النشاط الأخير</h2></div><Link to="/invitations" className="view-link">عرض الكل <ArrowLeft size={14} /></Link></div><EmptyState title="لا توجد نشاطات حديثة" description="ستظهر هنا آخر التحديثات والنشاطات عند بدء استخدام المنصة." /></section><section className="dashboard-panel"><div className="panel-heading"><div><p className="eyebrow">الجدول</p><h2>نظرة على المواعيد</h2></div><Clock3 size={19} className="panel-icon" /></div><div className="appointment-placeholder"><CalendarDays size={22} /><strong>لا توجد مواعيد اليوم</strong><span>سيظهر ملخص المواعيد بعد ربط النظام.</span></div></section></div><section className="quick-actions"><div className="panel-heading"><div><p className="eyebrow">الإجراءات</p><h2>وصول سريع</h2></div></div><div className="action-grid"><Link to="/organizations" className="action-card"><span className="stat-icon blue"><Building2 size={19} /></span><span><strong>إضافة مؤسسة</strong><small>أنشئ مساحة جديدة</small></span><ArrowLeft size={16} /></Link><Link to="/clinics" className="action-card"><span className="stat-icon teal"><Stethoscope size={19} /></span><span><strong>إضافة عيادة</strong><small>اربط عيادة بمؤسسة</small></span><ArrowLeft size={16} /></Link><Link to="/invitations" className="action-card"><span className="stat-icon amber"><Users size={19} /></span><span><strong>دعوة عضو</strong><small>وسّع فريقك</small></span><ArrowLeft size={16} /></Link><div className="privacy-note"><Activity size={18} /><span><strong>الخصوصية أولًا</strong><small>لا توجد بيانات حساسة في هذه الواجهة.</small></span><StatusBadge label="جاهز" tone="success" /></div></div></section></>
}